/**
 * Epistemological Invariants — the constitution of the AI radio system.
 *
 * These are NOT features. They are NOT configurable. They are the rules that
 * distinguish a system that learns from a system that tells stories about itself.
 *
 * See: docs/EPISTEMOLOGICAL-INVARIANTS.md for the full rationale and audit.
 *
 * The One Principle:
 *   Do not write what the AI thinks happened. Write what actually happened.
 *
 * Usage:
 *   import { EPISTEMOLOGICAL_INVARIANTS, checkConfidenceInvariant, type MemorySource } from '@/lib/ai-core/invariants'
 *
 *   // Before storing a memory entry:
 *   if (entry.confidence.level === 'very-high' && entry.isReal === false) {
 *     // VIOLATION of Invariant 5 — Honest Confidence
 *     // A predicted/demonstration entry may not carry very-high confidence.
 *   }
 *
 * This module is deliberately small and dependency-free. It is referenced by
 * station-memory, knowledge-engine, and learning-loop. It must never import
 * from those modules — the dependency direction is one-way.
 */

/**
 * The provenance of a memory entry. Every long-term memory entry MUST carry
 * one of these three values. Absence of a source is treated as `predicted`.
 *
 * - `measured`: observed from real listener behavior through a real pipeline.
 *   Only this source may carry confidence above `medium`.
 *
 * - `human-asserted`: stated by an operator, with their name and the date.
 *   May influence decisions, but confidence is bounded and the entry must be
 *   flagged for later measurement.
 *
 * - `predicted`: generated by the AI, never yet confirmed by reality.
 *   May never carry confidence above `medium` (Invariant 5).
 */
export type MemorySource = 'measured' | 'human-asserted' | 'predicted'

/**
 * The seven invariants. The `id` is stable across versions and is used in
 * audit records. The `statement` is the one-line rule. The `appliesTo` lists
 * the modules that must comply.
 */
export const EPISTEMOLOGICAL_INVARIANTS = [
  {
    id: 'reality',
    statement:
      'No AI prediction may be stored as fact. Every memory entry carries source: measured | human-asserted | predicted.',
    appliesTo: ['station-memory', 'knowledge-engine', 'learning-loop'],
  },
  {
    id: 'prediction-reality-separation',
    statement:
      'For every AI-influenced decision, the system stores the prediction, the actual outcome, and the signed difference — separately.',
    appliesTo: ['station-memory', 'learning-loop'],
  },
  {
    id: 'failure-preservation',
    statement:
      'Failed predictions are never deleted, overwritten, or silently corrected. The Learning Loop must consume them.',
    appliesTo: ['station-memory', 'knowledge-engine', 'learning-loop'],
  },
  {
    id: 'sample-size',
    statement:
      'No claim may be promoted to rule status without a stated sample size. Confidence without n is a feeling, not a score.',
    appliesTo: ['station-memory', 'knowledge-engine', 'learning-loop'],
  },
  {
    id: 'honest-confidence',
    statement:
      'Predictions cap at 0.75. Only externally-validated facts exceed 0.90. very-high confidence with isReal=false is incoherent.',
    appliesTo: ['station-memory', 'knowledge-engine', 'learning-loop'],
  },
  {
    id: 'counterfactual-honesty',
    statement:
      'Causal claims require a recorded counterfactual. "Versus what" is the claim.',
    appliesTo: ['station-memory', 'knowledge-engine', 'learning-loop'],
  },
  {
    id: 'legend-prevention',
    statement:
      'The AI may not write to long-term memory in its own voice. Every entry traces to measured data or a human assertion — never to an AI reflection.',
    appliesTo: ['station-memory', 'learning-loop'],
  },
] as const

export type InvariantId = (typeof EPISTEMOLOGICAL_INVARIANTS)[number]['id']

// ---------------------------------------------------------------------------
// Confidence caps — Invariant 5 (Honest Confidence)
// ---------------------------------------------------------------------------

/**
 * The maximum confidence a `predicted` (non-measured) entry may carry.
 * Above this value, the entry MUST have source === 'measured' and isReal === true.
 */
export const PREDICTED_CONFIDENCE_CAP = 0.75

/**
 * The minimum confidence threshold for a claim to be considered
 * "externally validated." Below this, a claim is a hypothesis, not a rule.
 */
export const EXTERNAL_VALIDATION_THRESHOLD = 0.9

/**
 * Reserved for tautologies and direct unprocessed measurements.
 * The system should almost never assign this value.
 */
export const MAXIMUM_CONFIDENCE = 0.99

// ---------------------------------------------------------------------------
// Compliance checkers
// ---------------------------------------------------------------------------

export interface ConfidenceCheckInput {
  /** Numeric confidence in [0, 1], or a level label. */
  confidence?: number | 'very-high' | 'high' | 'medium' | 'low' | 'experimental'
  /** Whether the underlying evidence comes from real operation. */
  isReal: boolean
  /** Provenance of the entry. Defaults to 'predicted' if absent. */
  source?: MemorySource
}

export interface InvariantViolation {
  invariant: InvariantId
  severity: 'error' | 'warning'
  message: string
}

/**
 * Check Invariant 5 — Honest Confidence.
 *
 * Returns a violation if:
 *   - a non-measured entry carries confidence above PREDICTED_CONFIDENCE_CAP, or
 *   - a labeled level is 'very-high' or 'high' while isReal is false.
 *
 * This is the checker that would have caught the lesson-001 finding in the
 * 2026-07-13 audit (very-high confidence, 847 observations, isReal=false).
 */
export function checkConfidenceInvariant(
  input: ConfidenceCheckInput,
): InvariantViolation | null {
  const source: MemorySource = input.source ?? 'predicted'

  // Label-based check (station-memory lessons use labels)
  if (typeof input.confidence === 'string') {
    if (
      (input.confidence === 'very-high' || input.confidence === 'high') &&
      input.isReal === false
    ) {
      return {
        invariant: 'honest-confidence',
        severity: 'error',
        message: `Confidence level "${input.confidence}" is incoherent with isReal=false. A predicted/demonstration entry may carry at most "medium" confidence (Invariant 5). Either lower the confidence or wait until a real measurement supports it.`,
      }
    }
    return null
  }

  // Numeric check (knowledge-engine / learning-loop use scores)
  if (typeof input.confidence === 'number') {
    if (source !== 'measured' && input.confidence > PREDICTED_CONFIDENCE_CAP) {
      return {
        invariant: 'honest-confidence',
        severity: 'error',
        message: `Confidence ${input.confidence} exceeds the predicted-entry cap of ${PREDICTED_CONFIDENCE_CAP} for source="${source}". Either lower the confidence or upgrade the source to 'measured' with real evidence.`,
      }
    }
    if (
      input.confidence >= EXTERNAL_VALIDATION_THRESHOLD &&
      input.isReal === false
    ) {
      return {
        invariant: 'honest-confidence',
        severity: 'warning',
        message: `Confidence ${input.confidence} meets the external-validation threshold but isReal=false. This entry will be promoted only when a real A/B test confirms it.`,
      }
    }
  }

  return null
}

/**
 * Check Invariant 7 — Legend Prevention.
 *
 * Returns a violation if a memory entry contains an AI-authored reflection
 * field (e.g. `aiSelfReflection`, `selfAwareness`) that is stored as part of
 * the permanent record without a corresponding `measured` counterpart.
 *
 * The reflection is allowed to exist — the AI is allowed to think out loud.
 * What is NOT allowed is for that reflection to be promoted to memory in the
 * AI's own voice. It must be re-cast as a prediction (source: 'predicted')
 * and measured later.
 *
 * @param fields - the field names present on the entry being stored
 * @param hasMeasuredCounterpart - whether a measured field covers the same claim
 */
export function checkLegendPreventionInvariant(args: {
  fields: string[]
  hasMeasuredCounterpart: boolean
}): InvariantViolation | null {
  const aiVoiceFields = ['aiSelfReflection', 'selfAwareness', 'aiNarrative']
  const present = args.fields.filter((f) => aiVoiceFields.includes(f))

  if (present.length === 0) return null

  if (!args.hasMeasuredCounterpart) {
    return {
      invariant: 'legend-prevention',
      severity: 'warning',
      message: `Entry contains AI-voice field(s) [${present.join(', ')}] with no measured counterpart. The AI's reflection is allowed as a prediction (source: 'predicted'), but it must not be the final memory of the event. Either pair it with a measured field or label it source='predicted' explicitly.`,
    }
  }

  return null
}

/**
 * Run all applicable invariant checks on a memory entry.
 * Returns the list of violations (empty if the entry is compliant).
 */
export function auditMemoryEntry(entry: {
  confidence?: number | string
  isReal: boolean
  source?: MemorySource
  fields?: string[]
  hasMeasuredCounterpart?: boolean
}): InvariantViolation[] {
  const violations: InvariantViolation[] = []

  const c = checkConfidenceInvariant({
    confidence: entry.confidence as ConfidenceCheckInput['confidence'],
    isReal: entry.isReal,
    source: entry.source,
  })
  if (c) violations.push(c)

  if (entry.fields) {
    const l = checkLegendPreventionInvariant({
      fields: entry.fields,
      hasMeasuredCounterpart: entry.hasMeasuredCounterpart ?? false,
    })
    if (l) violations.push(l)
  }

  return violations
}

/**
 * The full audit manifest, for any module that wants to expose which
 * invariants it currently upholds, partially upholds, or violates.
 *
 * This is what produced the audit table in docs/EPISTEMOLOGICAL-INVARIANTS.md.
 * Modules should not lie about their status — a known violation is a managed
 * risk; an unknown violation is a rotting foundation.
 */
export interface ModuleCompliance {
  module: string
  status: Partial<Record<InvariantId, 'upheld' | 'partial' | 'violated'>>
  lastAudited: string
  notes?: string[]
}

/**
 * The 2026-07-13 audit baseline. This is the honest state of the system
 * as of the Framework Year. Future audits append to this, they do not
 * overwrite it — see Invariant 3 (Failure Preservation) applied to the
 * audit itself.
 */
export const AUDIT_BASELINE_2026: ModuleCompliance[] = [
  {
    module: 'station-memory',
    status: {
      reality: 'partial',
      'prediction-reality-separation': 'partial',
      'failure-preservation': 'upheld',
      'sample-size': 'partial',
      'honest-confidence': 'violated',
      'counterfactual-honesty': 'partial',
      'legend-prevention': 'violated',
    },
    lastAudited: '2026-07-13',
    notes: [
      'Violated: lesson-001 has level=very-high with isReal=false (Invariant 5).',
      'Violated: Journal aiSelfReflection field is AI narrating in first person (Invariant 7).',
      'Partial: Segments lack sample size on avgSessionMin / returnRate7d / churnRisk (Invariant 4).',
      'Partial: Lessons lack explicit counterfactuals (Invariant 6).',
    ],
  },
  {
    module: 'knowledge-engine',
    status: {
      reality: 'partial',
      'prediction-reality-separation': 'upheld',
      'failure-preservation': 'upheld',
      'sample-size': 'upheld',
      'honest-confidence': 'violated',
      'counterfactual-honesty': 'partial',
      'legend-prevention': 'upheld',
    },
    lastAudited: '2026-07-13',
    notes: [
      'Violated: confidence.score=45 with isReal=false is inflated (Invariant 5).',
      'Partial: rules state effect size but not the explicit counterfactual "versus what" (Invariant 6).',
      'Upheld: every evidence carries sampleSize (Invariant 4).',
      'Upheld: superseded rules marked deprecated, kept in history (Invariant 3).',
    ],
  },
  {
    module: 'learning-loop',
    status: {
      reality: 'upheld',
      'prediction-reality-separation': 'upheld',
      'failure-preservation': 'upheld',
      'sample-size': 'upheld',
      'honest-confidence': 'upheld',
      'counterfactual-honesty': 'upheld',
      'legend-prevention': 'violated',
    },
    lastAudited: '2026-07-13',
    notes: [
      'Gold standard: projectedOutcome / actualOutcome / surprise / confounders / causalConfidence cleanly separated.',
      'Violated: selfAwareness field ["I underestimate..."] is AI narrating in first person (Invariant 7).',
      'Upheld: causalConfidence tied to A/B validation status (Invariant 5).',
      'Upheld: confounders note n=1 where applicable (Invariant 4).',
    ],
  },
]
